# Generated by Django 2.0.2 on 2018-06-09 08:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Band',
                'verbose_name_plural': 'Bands',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=20)),
                ('origin_country', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Brand',
                'verbose_name_plural': 'Brands',
            },
        ),
        migrations.CreateModel(
            name='Mobile',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('model', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=10)),
                ('price', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('proccessor_speed', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)])),
                ('band', models.ManyToManyField(to='mobile.Bands')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='mobile.Brand')),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Mobile',
                'verbose_name_plural': 'Mobiles',
            },
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=10)),
                ('version', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('id',),
                'verbose_name': 'Operating System',
                'verbose_name_plural': 'Operating Systems',
            },
        ),
        migrations.AddField(
            model_name='mobile',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_system', to='mobile.OS'),
        ),
    ]
