# Generated by Django 2.0.2 on 2018-06-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mobile',
            name='band',
            field=models.ManyToManyField(related_name='band', to='mobile.Bands'),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='model',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='mobile',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
